groups:
  - name: llm
    rules:
      - alert: LLMFailuresBurst
        expr: increase(llm_failures[15m]) > 3
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "LLM failures spike"
          description: "Check OpenAI/Flowise availability"
      - alert: LLMValidationWarnings
        expr: increase(llm_validation{type="analyst"}[30m]) > 5
        labels:
          severity: warning
        annotations:
          summary: "LLM validation warnings"
          description: "Analyst outputs contain repeated issues"
  - name: forecast
    rules:
      - alert: ForecastQualityDegradation
        expr: forecast_quality_smape > 0.12
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "SMAPE exceeds threshold"
          description: "Investigate recent forecasts"
